# Generated by Django 4.2.17 on 2024-12-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bookName", models.CharField(blank=True, max_length=200, null=True)),
                ("category", models.CharField(blank=True, max_length=200, null=True)),
                ("count_char", models.CharField(blank=True, max_length=100, null=True)),
                ("cover", models.URLField(blank=True, null=True)),
                ("authors", models.CharField(blank=True, max_length=200, null=True)),
                ("count_click", models.CharField(blank=True, max_length=50, null=True)),
                ("introduction", models.TextField(blank=True, null=True)),
                ("sourceUrl", models.URLField(blank=True, max_length=250, null=True)),
                ("sourceName", models.CharField(blank=True, max_length=50, null=True)),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
                ("tag", models.CharField(blank=True, max_length=255, null=True)),
                ("score", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "books",
            },
        ),
    ]
